# Generated by Django 4.1.4 on 2023-07-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyServiceAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('period', models.CharField(choices=[('ONE_MONTH', '1 Месяц'), ('THREE_MONTHS', '3 Месяца'), ('SIX_MONTHS', '6 Месяцев'), ('TWELVE_MONTHS', '12 Месяцев')], default='ONE_MONTH', max_length=50, verbose_name='Период')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyServiceCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('period', models.CharField(choices=[('ONE_MONTH', '1 Месяц'), ('THREE_MONTHS', '3 Месяца'), ('SIX_MONTHS', '6 Месяцев'), ('TWELVE_MONTHS', '12 Месяцев')], default='ONE_MONTH', max_length=50, verbose_name='Период')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'abstract': False,
            },
        ),
    ]
