# Generated by Django 4.1.4 on 2023-03-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('period', models.CharField(choices=[('ONE_MONTH', '1 Месяц'), ('THREE_MONTHS', '3 Месяца'), ('SIX_MONTHS', '6 Месяцев'), ('TWELVE_MONTHS', '12 Месяцев')], default='ONE_MONTH', max_length=50, verbose_name='Период')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуги для компании',
                'verbose_name_plural': 'Услуги для компаний',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('subscribed_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('expiring_on', models.DateTimeField(verbose_name='Дата истечения подписки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='companies.company', verbose_name='Компании')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.serviceproduct', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Подписка компании',
                'verbose_name_plural': 'Подписки компаний',
            },
        ),
    ]
