# Generated by Django 4.1.4 on 2023-07-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyServiceAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('period', models.CharField(choices=[('30', '1 Месяц'), ('90', '3 Месяца'), ('180', '6 Месяцев'), ('360', '12 Месяцев')], default='30', max_length=50, verbose_name='Период')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услугу Агрегатора',
                'verbose_name_plural': 'Услуги Агрегатора',
            },
        ),
        migrations.CreateModel(
            name='CompanyServiceCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('period', models.CharField(choices=[('30', '1 Месяц'), ('90', '3 Месяца'), ('180', '6 Месяцев'), ('360', '12 Месяцев')], default='30', max_length=50, verbose_name='Период')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услугу CRM',
                'verbose_name_plural': 'Услуги CRM',
            },
        ),
    ]
