# Generated by Django 4.1.4 on 2023-07-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyserviceaggregation',
            options={'verbose_name': 'Услугу Агрегатора', 'verbose_name_plural': 'Услуги Агрегатора'},
        ),
        migrations.AlterModelOptions(
            name='companyservicecrm',
            options={'verbose_name': 'Услугу CRM', 'verbose_name_plural': 'Услуги CRM'},
        ),
    ]
