# Generated by Django 4.1.4 on 2023-03-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
