# Generated by Django 4.1.4 on 2023-03-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('services', '0003_serviceproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='subscriptioncompany',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.serviceproduct'),
        ),
    ]
