# Generated by Django 4.1.4 on 2023-03-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('services', '0004_alter_subscriptioncompany_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='companies.company', verbose_name='Компании'),
        ),
        migrations.AlterField(
            model_name='subscriptioncompany',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.serviceproduct', verbose_name='Услуга'),
        ),
    ]
