# Generated by Django 3.2.19 on 2023-06-25 12:17

import companies.mixins
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефонный номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
            bases=(companies.mixins.CompanyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClientAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_quantity_days_for_order', models.IntegerField(blank=True, null=True, verbose_name='Среднее колл-во дней для одного заказа')),
                ('date_planned_next_order', models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата следующего заказа')),
            ],
            options={
                'verbose_name': 'Аналитика o клиенте',
                'verbose_name_plural': 'Аналитика o клиенте',
            },
        ),
        migrations.CreateModel(
            name='ClientStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_completed_orders', models.IntegerField(blank=True, null=True, verbose_name='Колл-во выполненных заказов')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client_statistics', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Статистика o клиенте',
                'verbose_name_plural': 'Статистика o клиенте',
            },
        ),
    ]
