# Generated by Django 4.1.4 on 2023-03-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='company',
        ),
    ]
