# Generated by Django 3.2.19 on 2023-06-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
        ('companies', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstatistics',
            name='first_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_client_statistics', to='orders.order', verbose_name='Первый выполненный заказ'),
        ),
        migrations.AddField(
            model_name='clientstatistics',
            name='last_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_client_statistics', to='orders.order', verbose_name='Последний выполненный заказ'),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='addresses.address', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='companies.company', verbose_name='Компания'),
        ),
    ]
