# Generated by Django 4.1.4 on 2023-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street'], name='address_street_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['home'], name='address_home_idx'),
        ),
    ]
