# Generated by Django 4.1.4 on 2023-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='client_is_active_idx'),
        ),
    ]
