# Generated by Django 3.2.19 on 2023-06-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientanalytics',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_analytics', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='clientstatistics',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_statistics', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='clientstatistics',
            name='first_completed_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_client_statistics', to='orders.order', verbose_name='Первый выполненный заказ'),
        ),
        migrations.AlterField(
            model_name='clientstatistics',
            name='last_completed_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_client_statistics', to='orders.order', verbose_name='Последний выполненный заказ'),
        ),
    ]
