# Generated by Django 3.2.19 on 2023-06-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstatistics',
            name='date_order_planned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата следующего заказа'),
        ),
    ]
