# Generated by Django 4.1.4 on 2023-03-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_region_alter_city_options_alter_city_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
