# Generated by Django 3.2.19 on 2023-06-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clientstatistics_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientstatistics',
            name='average_date_orders',
        ),
        migrations.RemoveField(
            model_name='clientstatistics',
            name='date_planned_next_order',
        ),
        migrations.CreateModel(
            name='ClientAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_date_orders', models.IntegerField(blank=True, null=True, verbose_name='Среднее колл-во дней для одного заказа')),
                ('date_planned_next_order', models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата следующего заказа')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client_analytics', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Аналитика o клиенте',
                'verbose_name_plural': 'Аналитика o клиенте',
            },
        ),
    ]
