# Generated by Django 4.1.4 on 2023-03-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_region_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(default=1, max_length=255, verbose_name='Область'),
            preserve_default=False,
        ),
    ]
