# Generated by Django 4.1.4 on 2023-03-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_address_country_region_country_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='address_street_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
