# Generated by Django 4.1.4 on 2023-03-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_address_address_street_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='address_home_idx',
        ),
    ]
