# Generated by Django 4.1.4 on 2023-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_address_address_home_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default=1, max_length=255, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street'], name='address_street_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['home'], name='address_home_idx'),
        ),
    ]
