# Generated by Django 4.1.4 on 2023-03-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_address_city_address_country_address_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='clients.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='clients.street', verbose_name='Улица'),
        ),
    ]
