# Generated by Django 4.1.4 on 2023-03-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_remove_address_address_street_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.street', verbose_name='Улица'),
        ),
    ]
