# Generated by Django 4.1.4 on 2023-03-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_address_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='clients.street', verbose_name='Улица'),
        ),
    ]
