version: '3.4'

services:
  bot:
    image: bot
    build:
      context: bot/
      dockerfile: Dockerfile
    restart: always
    command: python main.py
    volumes:
      - ./bot:/app/bot
    env_file:
      - .env
  crm_django:
    container_name: crm_django
    build:
      context: osenezator/
      dockerfile: Dockerfile
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./osenezator:/app/django
    env_file:
      - .env

