version: '3.4'

services:
  bot:
    image: bot
    build:
      context: bot/
      dockerfile: Dockerfile
    restart: always
    command: python main.py
    # volumes:
    #   - ./bot:/app/bot
    env_file:
      - .env
  web:
    build:
        context: unearth/
        dockerfile: Dockerfile
    ports:
    - "8080:7000"
  crm_django:
    build:
      context: osenezator/
      dockerfile: Dockerfile
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    # volumes:
    #   - ./osenezator:/app/django
    env_file:
      - .env

