# Generated by Django 4.1.4 on 2022-12-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('drivers', '0002_driver_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
