# Generated by Django 4.1.4 on 2022-12-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name car')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Volume')),
                ('number', models.CharField(max_length=255, verbose_name='Number car')),
            ],
        ),
    ]
