# Generated by Django 4.1.4 on 2022-12-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_carmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModel',
            new_name='Car',
        ),
    ]
