# Generated by Django 4.1.4 on 2023-06-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0007_alter_accountingcompany_options'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
    ]
