# Generated by Django 4.1.4 on 2023-02-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_telegram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telegram',
        ),
    ]
