# Generated by Django 4.1.4 on 2023-02-16 17:46

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_date_completed_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='Дата завершения', when={'COMPLETED'}),
        ),
    ]
