# Generated by Django 4.1.4 on 2023-02-16 18:17

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_date_alter_order_date_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='Дата завершения', when={'COMPLETED'}),
        ),
    ]
