# Generated by Django 3.2.19 on 2023-06-15 22:51

import companies.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('OWNER', 'Владелец'), ('DRIVER', 'Водитель'), ('DISPATCHER', 'Диспетчер')], max_length=20, verbose_name='Тип пользователя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефонный номер')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Компания')),
                ('telegram', models.OneToOneField(blank=True, help_text='Введите username без "@"', null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
            bases=(companies.mixins.CompanyMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user_type'], name='profile_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['telegram_id'], name='profile_telegram_id_idx'),
        ),
    ]
