# Generated by Django 4.1.4 on 2023-06-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Телеграм профиль',
                'verbose_name_plural': 'Телеграм профили',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.OneToOneField(blank=True, help_text='Введите username без "@"', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.telegram'),
        ),
    ]
