# Generated by Django 4.1.4 on 2023-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user_type'], name='profile_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['telegram_id'], name='profile_telegram_id_idx'),
        ),
    ]
