# Generated by Django 4.1.4 on 2023-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(default=1, max_length=20, verbose_name='telegram_id'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Telegram',
        ),
    ]
