# Generated by Django 4.1.4 on 2023-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_telegram_id_delete_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telegram_id'),
        ),
    ]
