# Generated by Django 4.1.4 on 2023-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='work_of_streets',
            field=models.ManyToManyField(related_name='companies', to='addresses.street', verbose_name='Улицы из которых принимаются заказы'),
        ),
    ]
