# Generated by Django 3.2.19 on 2023-06-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplacecompany',
            name='date_created',
        ),
    ]
