# Generated by Django 4.1.4 on 2023-04-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceProductCompany',
            new_name='ServiceCompany',
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
    ]
