# Generated by Django 4.1.4 on 2023-07-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyServiceAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('period', models.CharField(choices=[('ONE_MONTH', '1 Месяц'), ('THREE_MONTHS', '3 Месяца'), ('SIX_MONTHS', '6 Месяцев'), ('TWELVE_MONTHS', '12 Месяцев')], default='ONE_MONTH', max_length=50, verbose_name='Период')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='CompanyServiceSubscriptionCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('period', models.CharField(choices=[('ONE_MONTH', '1 Месяц'), ('THREE_MONTHS', '3 Месяца'), ('SIX_MONTHS', '6 Месяцев'), ('TWELVE_MONTHS', '12 Месяцев')], default='ONE_MONTH', max_length=50, verbose_name='Период')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('date_subscribed_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('date_subscribed_off', models.DateTimeField(verbose_name='Дата истечения подписки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='companies.company', verbose_name='Компании')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Подписка компании',
                'verbose_name_plural': 'Подписки компаний',
            },
        ),
    ]
