# Generated by Django 3.2.19 on 2023-06-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('companies', '0002_remove_workplacecompany_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountingCompany',
            new_name='CompanyAccounting',
        ),
        migrations.RenameModel(
            old_name='WorkPlaceCompany',
            new_name='CompanyWorkPlace',
        ),
    ]
