# Generated by Django 4.1.4 on 2023-04-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_work_of_streets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='work_of_cities',
            new_name='cities',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='work_of_streets',
            new_name='streets',
        ),
    ]
