# Generated by Django 4.1.4 on 2023-06-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_districts_company_regions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='country',
            new_name='countries',
        ),
    ]
