# Generated by Django 4.1.4 on 2023-07-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyserviceaggregation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyServiceSubscriptionCRM',
            new_name='CompanyServiceCRM',
        ),
    ]
