# Generated by Django 4.1.4 on 2023-06-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_district_city'),
        ('companies', '0003_rename_country_company_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='company',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='company',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='company',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='company',
            name='streets',
        ),
        migrations.CreateModel(
            name='WorkPlaceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cities', models.ManyToManyField(related_name='companies', to='addresses.city', verbose_name='Города или Населенные пункты из которых принимаются заказы')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_place', to='companies.company')),
                ('countries', models.ManyToManyField(related_name='companies', to='addresses.country', verbose_name='Страны из которых принимаются заказы')),
                ('districts', models.ManyToManyField(related_name='companies', to='addresses.district', verbose_name='Районы которых принимаются заказы')),
                ('regions', models.ManyToManyField(related_name='companies', to='addresses.region', verbose_name='Регионы из которых принимаются заказы')),
                ('streets', models.ManyToManyField(related_name='companies', to='addresses.street', verbose_name='Улицы из которых принимаются заказы')),
            ],
            options={
                'verbose_name': 'Прием заказов',
                'verbose_name_plural': 'Прием заказов',
            },
        ),
    ]
