# Generated by Django 4.1.4 on 2023-07-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_companyservicesubscriptioncrm_companyservicecrm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyServiceAggregation',
        ),
        migrations.DeleteModel(
            name='CompanyServiceCRM',
        ),
    ]
