# Generated by Django 4.1.4 on 2023-03-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_serviceproductcompany_subscriptioncompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город или населенный пункт',
                'verbose_name_plural': 'Города или населенные пункты',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='city_name_idx'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_of_cities',
            field=models.ManyToManyField(related_name='work_of_cities', to='companies.city', verbose_name='Города или Населенные пункты из которых принимаются заказы'),
        ),
    ]
