# Generated by Django 4.1.4 on 2023-07-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_delete_companyserviceaggregation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyworkplace',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='companyworkplace',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='companyworkplace',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='companyworkplace',
            name='streets',
        ),
    ]
