# Generated by Django 4.1.4 on 2023-06-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_cities_remove_company_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
    ]
