# Generated by Django 4.1.4 on 2023-07-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_companyworkplace_cities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyworkplace',
            options={'verbose_name': 'Место где агрегатор куда добавлять заказы', 'verbose_name_plural': 'Место где агрегатор куда добавлять заказы'},
        ),
    ]
