# Generated by Django 4.1.4 on 2023-06-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_company_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingcompany',
            options={'verbose_name': 'Аккаунтинг', 'verbose_name_plural': 'Аккаунтинг'},
        ),
    ]
