# Generated by Django 4.1.4 on 2023-07-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_companyworkplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyworkplace',
            options={'verbose_name': 'Область куда агрегатор будет добавлять заказы', 'verbose_name_plural': 'Области куда агрегатор будет добавлять заказы'},
        ),
    ]
