# Generated by Django 3.2.19 on 2023-06-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_accountingcompany_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplacecompany',
            name='districts',
        ),
    ]
