# Generated by Django 4.1.4 on 2023-03-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_alter_street_city'),
        ('companies', '0007_alter_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='clients.country', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
