# Generated by Django 4.1.4 on 2023-02-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='count_new_clients',
            field=models.IntegerField(default=0, verbose_name='Колличетсво новых клиентов'),
        ),
    ]
