# Generated by Django 4.1.4 on 2023-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_count_new_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='count_orders',
            field=models.IntegerField(null=True, verbose_name='Колличество заказов'),
        ),
    ]
