# Generated by Django 4.1.4 on 2023-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_count_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='count_new_addresses',
            field=models.IntegerField(default=0, null=True, verbose_name='Колличетсво новых адресов'),
        ),
    ]
