# Generated by Django 4.1.4 on 2023-02-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_count_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='count_new_addresses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колличетсво новых адресов'),
        ),
        migrations.AlterField(
            model_name='report',
            name='count_new_clients',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колличетсво новых клиентов'),
        ),
        migrations.AlterField(
            model_name='report',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Прибыль'),
        ),
    ]
