# Generated by Django 4.1.4 on 2023-07-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegram',
            name='telegram_username_idx',
        ),
    ]
