# Generated by Django 4.1.4 on 2023-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.RemoveField(
            model_name='city',
            name='title',
        ),
        migrations.RemoveField(
            model_name='country',
            name='title',
        ),
        migrations.RemoveField(
            model_name='region',
            name='title',
        ),
        migrations.RemoveField(
            model_name='street',
            name='title',
        ),
        migrations.AddField(
            model_name='address',
            name='home',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='uid',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Уникальный номер города'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='uid',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Уникальный номер региона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='uid',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Уникальный номер региона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='street',
            name='uid',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Уникальный номер улицы'),
            preserve_default=False,
        ),
    ]
