# Generated by Django 4.1.4 on 2023-07-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_remove_address_home_address_name_address_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='home',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='addresses.street', verbose_name='Улица'),
        ),
    ]
