# Generated by Django 3.2.19 on 2023-06-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_workplacecompany_districts'),
        ('addresses', '0004_alter_district_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.RemoveField(
            model_name='street',
            name='district',
        ),
        migrations.AddField(
            model_name='street',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='addresses.city', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='addresses.country', verbose_name='Страна'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
