# Generated by Django 4.1.4 on 2023-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_remove_address_name_address_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название адреса'),
        ),
    ]
