# Generated by Django 4.1.4 on 2023-07-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_companyworkplace_cities_and_more'),
        ('addresses', '0006_remove_address_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='street',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
