# Generated by Django 3.2.19 on 2023-06-05 14:14

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='Дата конца выполнения', when={'COMPLETED'}),
        ),
    ]
