# Generated by Django 4.1.4 on 2023-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_created'], name='order_date_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_sent'], name='order_is_sent_idx'),
        ),
    ]
