# Generated by Django 3.2.19 on 2023-06-22 19:55

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_canceled',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='Дата отмены выполнения', when={'CANCELED'}),
        ),
    ]
