# Generated by Django 4.1.4 on 2023-03-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_serviceproductcompany_subscriptioncompany'),
        ('orders', '0002_order_order_status_idx_order_order_date_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='companies.company', verbose_name='Компания'),
        ),
    ]
