# Generated by Django 4.1.4 on 2023-04-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0004_alter_order_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='employees.dispatcher', verbose_name='Диспетчер'),
        ),
    ]
