# Generated by Django 4.1.4 on 2023-02-16 18:18

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_date_alter_order_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=model_utils.fields.MonitorField(blank=True, default=None, editable=False, monitor='status', null=True, verbose_name='Дата завершения', when={'COMPLETED'}),
        ),
    ]
