# Generated by Django 4.1.4 on 2023-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_updated_order_date_planned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_planned',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Планируемая дата выполнения'),
        ),
    ]
