# Generated by Django 4.1.4 on 2023-02-16 19:56

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_date_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=model_utils.fields.StatusField(choices=[('CONFIRMATION', 'Подтверждение'), ('CONFIRMED', 'Подтвержден'), ('INPROGRESS', 'Выполняется'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменен')], default='CONFIRMED', max_length=100, no_check_for_status=True, verbose_name='Статус'),
        ),
    ]
