# Generated by Django 4.1.4 on 2023-02-18 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_start',
            new_name='date_started',
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
