# Generated by Django 4.1.4 on 2023-03-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_is_sent_alter_order_date_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_sent',
            new_name='is_showed',
        ),
    ]
