# Generated by Django 4.1.4 on 2023-03-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_alter_client_address_alter_client_company'),
        ('companies', '0001_initial'),
        ('orders', '0018_alter_order_is_showed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_payment',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CREDIT_CARD', 'Картой'), ('ONLINE_TRANSFER', 'Онлайн перевод')], default='ONLINE_TRANSFER', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_planned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_planned', models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата выполнения')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='clients.address')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
