# Generated by Django 4.1.4 on 2023-03-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_car_company'),
        ('orders', '0020_alter_order_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='employees.dispatcher'),
        ),
    ]
