# Generated by Django 4.1.4 on 2023-03-26 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_alter_client_address_alter_client_company'),
        ('orders', '0022_alter_order_dispatcher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_showed',
            new_name='is_sent',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='Дата выполнения', when={'COMPLETED'}),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Диспетчер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.DeleteModel(
            name='OrderTicket',
        ),
    ]
