# Generated by Django 4.1.4 on 2023-03-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_rename_is_showed_order_is_sent_alter_order_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
